/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package redes;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo de Dijkstra");
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tf1.setEditable(false);
        tf1.setBackground(new java.awt.Color(204, 153, 255));
        tf1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf1.setText("0");

        tf2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf12.setBackground(new java.awt.Color(204, 153, 255));
        tf12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        calcular.setBackground(new java.awt.Color(204, 153, 255));
        calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpar.setBackground(new java.awt.Color(204, 153, 255));
        limpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calcular)
                        .addGap(31, 31, 31)
                        .addComponent(limpar)
                        .addGap(14, 14, 14)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(limpar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        tf2.setText("");
        tf2.setBackground(Color.white);
        tf3.setText("");
        tf3.setBackground(Color.white);
        tf4.setText("");
        tf4.setBackground(Color.white);
        tf5.setText("");
        tf5.setBackground(Color.white);
        tf6.setText("");
        tf6.setBackground(Color.white);
        tf7.setText("");
        tf7.setBackground(Color.white);
        tf8.setText("");
        tf8.setBackground(Color.white);
        tf9.setText("");
        tf9.setBackground(Color.white);
        tf10.setText("");
        tf10.setBackground(Color.white);
        tf11.setText("");
        tf11.setBackground(Color.white);
        tf12.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        int s[] = new int[10];
        s[0] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf3.getText()) + Integer.parseInt(tf4.getText()) + Integer.parseInt(tf8.getText()) + Integer.parseInt(tf12.getText());
        s[1] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf3.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf8.getText()) + Integer.parseInt(tf12.getText());
        s[2] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf3.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        s[3] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        s[4] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf8.getText()) + Integer.parseInt(tf12.getText());
        s[5] = Integer.parseInt(tf2.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf10.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        
        s[6] = Integer.parseInt(tf5.getText()) + Integer.parseInt(tf9.getText()) + Integer.parseInt(tf10.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        s[7] = Integer.parseInt(tf5.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf8.getText()) + Integer.parseInt(tf12.getText());
        s[8] = Integer.parseInt(tf5.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf7.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        s[9] = Integer.parseInt(tf5.getText()) + Integer.parseInt(tf6.getText()) + Integer.parseInt(tf10.getText()) + Integer.parseInt(tf11.getText()) + Integer.parseInt(tf12.getText());
        
        if(tf2.getText().equals("")||tf3.getText().equals("")||tf4.getText().equals("")||tf5.getText().equals("")||tf6.getText().equals("")||tf7.getText().equals("")||tf8.getText().equals("")||tf9.getText().equals("")||tf10.getText().equals("")||tf11.getText().equals("")||tf12.getText().equals("")){
            JOptionPane.showMessageDialog(jPanel1,"Preencha todos os campos!");
        } else {
            int q = 999999999;
            for(int i = 0; i<10; i++){
                if(s[i]<q){
                 q = s[i];
                }
            }
            if(q == s[0]){
             tf2.setBackground(new Color(204,153,255));
             tf3.setBackground(new Color(204,153,255));
             tf4.setBackground(new Color(204,153,255));
             tf8.setBackground(new Color(204,153,255));
            } else if(q == s[1]){
             tf2.setBackground(new Color(204,153,255));
             tf3.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf8.setBackground(new Color(204,153,255));
            }
            else if(q == s[2]){
             tf2.setBackground(new Color(204,153,255));
             tf3.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
            else if(q == s[3]){
             tf2.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
            else if(q == s[4]){
             tf2.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf8.setBackground(new Color(204,153,255));
            }
            else if(q == s[5]){
             tf2.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf10.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
            else if(q == s[6]){
             tf5.setBackground(new Color(204,153,255));
             tf9.setBackground(new Color(204,153,255));
             tf10.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
            else if(q == s[7]){
             tf5.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf8.setBackground(new Color(204,153,255));
            }
            else if(q == s[8]){
             tf5.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf7.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
            else {
             tf5.setBackground(new Color(204,153,255));
             tf6.setBackground(new Color(204,153,255));
             tf10.setBackground(new Color(204,153,255));
             tf11.setBackground(new Color(204,153,255));
            }
        
        }
        
    }//GEN-LAST:event_calcularActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
