/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dijkstra;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuário
 */
public class dijkstra extends javax.swing.JFrame {
int a,b,c,d,e,f,g,h,i,j,k;
int s1, s2, s3, s4, s5, s6, s7, s8, s9, s10;
    /**
     * Creates new form dijkstra
     */
    public dijkstra() {
        initComponents();
        t1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        b1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("0");
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });

        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });

        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t3FocusLost(evt);
            }
        });

        t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t4FocusLost(evt);
            }
        });

        t5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t5FocusLost(evt);
            }
        });

        t6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t6FocusLost(evt);
            }
        });

        t7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t7FocusLost(evt);
            }
        });

        t8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t8FocusLost(evt);
            }
        });

        t9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t9FocusLost(evt);
            }
        });

        t10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t10FocusLost(evt);
            }
        });

        t11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t11FocusLost(evt);
            }
        });

        t12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t12FocusLost(evt);
            }
        });

        b1.setText("CALCULAR");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(b1)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost


        // TODO add your handling code here:
    }//GEN-LAST:event_t1FocusLost

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost

a = Integer.parseInt(t2.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t2FocusLost

    private void t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusLost

b = Integer.parseInt(t3.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t3FocusLost

    private void t4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusLost

c = Integer.parseInt(t4.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t4FocusLost

    private void t5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t5FocusLost

d = Integer.parseInt(t5.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t5FocusLost

    private void t6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t6FocusLost

e = Integer.parseInt(t6.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t6FocusLost

    private void t7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t7FocusLost

f = Integer.parseInt(t7.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t7FocusLost

    private void t8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t8FocusLost

g = Integer.parseInt(t8.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t8FocusLost

    private void t9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t9FocusLost

h = Integer.parseInt(t9.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t9FocusLost

    private void t10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t10FocusLost

i = Integer.parseInt(t10.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t10FocusLost

    private void t11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t11FocusLost

j = Integer.parseInt(t11.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t11FocusLost

    private void t12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t12FocusLost

k = Integer.parseInt(t12.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_t12FocusLost

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

         s1 = a + b + c +g+ k;
         s2 = a + e + i + j + k;
         s3 = a + e + f + j +k; 
         s4 = a + e + f + g + k;
         s5 = a + b + f + j+ k;
         s6 = a + b + f + g + k;
         s7 = d + h + i + j + k;
         s8 = d + e + i + j + k;
         s9 = d + e + f + j + k;
         s10 = d + e + f +g+ k;
         
         //JOptionPane.showMessageDialog(null, s1);
         //JOptionPane.showMessageDialog(null, s2);
         //JOptionPane.showMessageDialog(null, s3);
         //JOptionPane.showMessageDialog(null, s4);
         //JOptionPane.showMessageDialog(null, s5);
         //JOptionPane.showMessageDialog(null, s6);
         //JOptionPane.showMessageDialog(null, s7);
         //JOptionPane.showMessageDialog(null, s8);
         //JOptionPane.showMessageDialog(null, s9);
         //JOptionPane.showMessageDialog(null, s10);
         
         if(s1<s2 && s1<s3 && s1<s4 && s1<s5 && s1<s6 && s1<s7 && s1<s8 && s1<s9 && s1<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->3->4->8->12\n" + "\t\t"+ s1);
        }
         
        else  if(s2<s1 && s2<s3 && s2<s4 && s2<s5 && s2<s6 && s2<s7 && s2<s8 && s2<s9 && s2<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->6->10->11->12\n" +"\t\t"+ s2);
        }
         
        else if(s3<s2 && s3<s1 && s3<s4 && s3<s5 && s3<s6 && s3<s7 && s3<s8 && s3<s9 && s3<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->6->7->11->12\n" + "\t\t"+ s3);
        }
         
        else if(s4<s2 && s4<s3 && s4<s1 && s4<s5 && s4<s6 && s4<s7 && s4<s8 && s4<s9 && s4<s10){

           JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->6->7->8->12\n" + "\t\t"+ s4);
       }
         
        else if(s5<s2 && s5<s3 && s5<s4 && s5<s1 && s5<s6 && s5<s7 && s5<s8 && s5<s9 && s5<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->3->7->11->12\n" + "\t\t"+ s5);
        }
         
        else if(s6<s2 && s6<s3 && s6<s4 && s6<s5 && s6<s1 && s6<s7 && s6<s8 && s6<s9 && s6<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->2->3->7->8->12\n" + "\t\t"+ s6);
        }
         
       else  if(s7<s2 && s7<s3 && s7<s4 && s7<s5 && s7<s6 && s7<s1 && s7<s8 && s7<s9 && s7<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->5->9->10->11->12\n" + "\t\t"+ s7);
       }
         
      else  if(s8<s2 && s8<s3 && s8<s4 && s8<s5 && s8<s6 && s8<s7 && s8<s1 && s8<s9 && s8<s10){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->5->6->10->11->12\n" + "\t\t"+s8);
        }
         
        else if(s9<s2 && s9<s3 && s9<s4 && s9<s5 && s9<s6 && s9<s7 && s9<s8 && s9<s1 && s9<s10){

            JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->5->6->7->11->12\n" + "\t\t"+s9);
        }
         
      else  if(s10<s2 && s10<s3 && s10<s4 && s10<s5 && s10<s6 && s10<s7 && s10<s8 && s10<s9 && s10<s1){

             JOptionPane.showMessageDialog(null,"MENOR CAMINHO:\n 1->5->6->7->8->12\n" + s10);
         }
        


// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dijkstra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dijkstra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
